/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shelin
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbLk = new javax.swing.JRadioButton();
        rbPr = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfAngkatan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfKota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfKelas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA TELKOM SCHOOLS MALANG");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 10, 470, 20);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("The Real Informatic Schools");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 30, 160, 16);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 890, 50);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit);
        btnEdit.setBounds(430, 10, 100, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave);
        btnSave.setBounds(10, 10, 90, 30);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete);
        btnDelete.setBounds(110, 10, 90, 30);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel4.add(btnClear);
        btnClear.setBounds(210, 10, 100, 30);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btnRefresh);
        btnRefresh.setBounds(320, 10, 100, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(250, 50, 640, 50);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "JenisKelamin", "Angkatan", "Kelas", "Email", "Kota Asal", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tData);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 620, 370);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(250, 100, 640, 440);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Isian Data SIswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(20, 20, 60, 14);

        tfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNISActionPerformed(evt);
            }
        });
        jPanel6.add(tfNIS);
        tfNIS.setBounds(20, 40, 170, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(20, 120, 70, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel6);
        jLabel6.setBounds(20, 180, 0, 0);

        rbLk.setText("Laki-laki");
        rbLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLkActionPerformed(evt);
            }
        });
        jPanel6.add(rbLk);
        rbLk.setBounds(20, 140, 70, 23);

        rbPr.setText("Perempuan");
        jPanel6.add(rbPr);
        rbPr.setBounds(90, 140, 79, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 370, 60, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 70, 60, 14);
        jPanel6.add(tfNama);
        tfNama.setBounds(20, 90, 170, 30);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Angkatan");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(20, 220, 60, 14);
        jPanel6.add(tfAngkatan);
        tfAngkatan.setBounds(20, 240, 170, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kota Asal");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 320, 60, 14);

        tfKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKotaActionPerformed(evt);
            }
        });
        jPanel6.add(tfKota);
        tfKota.setBounds(20, 340, 170, 30);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(20, 390, 170, 100);

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        jPanel6.add(tfEmail);
        tfEmail.setBounds(20, 290, 170, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 270, 60, 14);
        jPanel6.add(tfKelas);
        tfKelas.setBounds(20, 190, 170, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kelas");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(20, 170, 60, 14);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 10, 230, 500);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 50, 250, 520);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(902, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNISActionPerformed

    private void rbLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLkActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if("".equals(tfNIS.getText()) || "".equals(tfNama.getText()) || "".equals(tfAngkatan.getText()) || "".equals(taAlamat.getText()) || "".equals(tfEmail.getText()) || "".equals(jLabel20.getText()) || "".equals(tfKota.getText())) {
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
    } else {
        String JK = "";
        if (rbLk.isSelected()){
            JK = "L";
        }else{
            JK = "P";
        }
        
        String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Angkatan,Kelas,Email,AsalKota,Alamat) VALUES ('"+tfNIS.getText()+"','"
                +tfNama.getText()+"','"+JK+"','"+tfAngkatan.getText()+"','"+tfKelas.getText()
                +"','"+tfEmail.getText()+"','"+tfKota.getText()+"','"+taAlamat.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tData.getSelectedRow();
        if(baris != -1) {
            String NIS = tData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS ='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfNIS.setText("");
        tfNama.setText("");
        tfAngkatan.setText("");
        buttonGroup1.clearSelection();
        taAlamat.setText("");
        tfEmail.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if ("".equals(tfNIS.getText()) || "".equals(tfNama.getText()) || "".equals(tfAngkatan.getText())|| "".equals(taAlamat.getText())||"".equals(tfEmail.getText()) || "".equals(jLabel20.getText())||"".equals(tfKota.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (rbLk.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "+"WHERE Nama='"+tfNama.getText()+"',"+"WHERE JenisKelamin='"+JK+"',"+"WHERE Angkatan='"+jLabel20.getText()+"',"+"WHERE Kelas='"+tfAngkatan.getText()+"'"+"WHERE Email='"+tfEmail.getText()+"',"+"WHERE AsalKota='"+tfKota.getText()+"',"+"WHERE NIS='"+tfNIS.getText()+"',"+"WHERE Alamat='"+taAlamat+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Terupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Terupdate","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnEditActionPerformed

    private void tfKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKotaActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed
    public void selectData() {
                String kolom[] = {"NIS","Nama","JenisKelamin","Angkatan","Kelas","Email","KotaAsal","Alamat"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL ="SELECT * FROM t_siswa";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String NIS = rs.getString(1);
                        String Nama = rs.getString(2);
                        String JenisKelamin = rs.getString(3);
                        String Angkatan = rs.getString(4);
                        if ("L".equals(rs.getString(3))){
                            JenisKelamin = "Laki-laki";
                        }else{
                            JenisKelamin = "Perempuan";
                        }
                        String Kelas = rs.getString(5);
                        String Email = rs.getString(6);
                        String AsalKota = rs.getString(7);
                        String Alamat = rs.getString(8);
                        String data[] = {NIS,Nama,JenisKelamin,Angkatan,Kelas,Email,AsalKota,Alamat};
                        dtm.addRow(data);
                    }
                    } catch (SQLException ex) {
                       Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
                }
                tData.setModel(dtm);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbLk;
    private javax.swing.JRadioButton rbPr;
    private javax.swing.JTable tData;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfAngkatan;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfKota;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
